# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- contact

# Miscellaneous
google_analytics: UA-42218141-2
favicon: /favicon.png
twitter: angularjsdev
google_plus:
fb_image: https://darlanalv.es/covers/cover-fb.png
fb_admins:
fb_app_id:
